GET http://127.0.0.1:8000/products/ HTTP/1.1

###

POST  http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzQ3NTQwLCJpYXQiOjE3NzEzNDcyNDAsImp0aSI6ImI1NjE2ZDY1OWFlZjRmNmE4ODQxZTQ2YTVmZWRhYmEwIiwidXNlcl9pZCI6IjQifQ.VPZqz-qw5Rq3UIfMiLkoE97qVVXWzCIS9D_7oQ_txig

{
    "name":"Television",
    "price":200,
    "stock":4,
    "description":"This is the description of the television"
}


###


POST  http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username":"hashi",
    "password":"123456"
} 


###

POST  http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
   "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MTQzNDAwNSwiaWF0IjoxNzcxMzQ3NjA1LCJqdGkiOiJjNTY1YjBkZDg5NjM0YTM2OGQ2YjEyZmZjN2EyMGQwZCIsInVzZXJfaWQiOiI0In0.xb3pgfZ1h-smt2gBNY7ibKDLJf5_i91fqhPXIfyHkyQ"
} 


###


GET  http://127.0.0.1:8000/products/3/ HTTP/1.1




###


PUT http://127.0.0.1:8000/products/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxNTcwMjIwLCJpYXQiOjE3NzE1Njk5MjAsImp0aSI6IjI4ZjEzZTZlYThkYTQzYzJhYzlkZGM5ZTg3OGExN2MxIiwidXNlcl9pZCI6IjIifQ.ZZT1bZumA0YKvaPBu5RkXZefd-UB_0axT87AXSEcfT0

   {
  "name": "Velvet Underground & Nico",
  "description": "Nesciunt perferendis quos esse, assumenda commodi repudiandae provident architecto reprehenderit ullam tempore vitae, nam natus quam, reiciendis natus explicabo odio quidem, esse molestiae inventore modi ullam labore minus fuga.",
  "price": "15.99",
  "stock": 20
}



###

DELETE http://127.0.0.1:8000/products/1/ HTTP/1.1


###
GET  http://127.0.0.1:8000/orders/  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxNTk3NzYyLCJpYXQiOjE3NzE1OTc0NjIsImp0aSI6IjdhM2U5MzMzZTQxNjQ4YzJhNTcxYWZkM2NhZjI5OTNlIiwidXNlcl9pZCI6IjQifQ.9OkU0sy_b0Q2Aa6_wz9U_VM5tYrBbEm5vjckIrMlRoY

###

POST  http://127.0.0.1:8000/orders/  HTTP/1.1
Content-Type: application/json


{
    "status":"Pending",
    "user":1,
    "items":[
        {
            "product":2,
            "quantity":5
        }
          
    ]
}



###

PUT   http://127.0.0.1:8000/orders/1dc5aed5-28d4-4b3f-8e70-587440a781aa/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxNTcwMjIwLCJpYXQiOjE3NzE1Njk5MjAsImp0aSI6IjI4ZjEzZTZlYThkYTQzYzJhYzlkZGM5ZTg3OGExN2MxIiwidXNlcl9pZCI6IjIifQ.ZZT1bZumA0YKvaPBu5RkXZefd-UB_0axT87AXSEcfT0

{
    "status":"Confirmed",
    "user":2,
    "items":[
        {
            "product":2,
            "quantity":10
        }
          
    ]
}


